# Generated by Django 5.0.4 on 2024-05-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="user",
            new_name="seller",
        ),
    ]
