# Generated by Django 5.0.4 on 2024-05-06 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_rename_user_item_seller"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="seller",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="customer",
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
