# Generated by Django 5.0.4 on 2024-05-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_rename_seller_item_user_remove_cart_customer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="user",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="user",
            new_name="seller",
        ),
    ]
