# Generated by Django 5.0.4 on 2024-05-24 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_cart_created_at_cart_updated_at_cartitem_created_at_and_more"),
        ("user", "0002_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.address",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="purchased",
            field=models.BooleanField(default=False),
        ),
    ]
