# Generated by Django 5.0.4 on 2024-08-28 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0006_cart_address_cart_purchased"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="address",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="purchased",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
